// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFUEvMswmYSQE9iwfC8s39tvD7NvzFWnc',
    appId: '1:792815259769:web:8e596ebbdceccf80dc44a8',
    messagingSenderId: '792815259769',
    projectId: 'fyp-management-4dad2',
    authDomain: 'fyp-management-4dad2.firebaseapp.com',
    storageBucket: 'fyp-management-4dad2.firebasestorage.app',
    measurementId: 'G-PXGL2Y1E0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCU0Q1td9Lww3ONKoKjodBEhpyNy3OsbI',
    appId: '1:792815259769:android:c348483b9e007766dc44a8',
    messagingSenderId: '792815259769',
    projectId: 'fyp-management-4dad2',
    storageBucket: 'fyp-management-4dad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4nSKtGCTkJ61pbXdh0BdPYz4huS5_b2k',
    appId: '1:792815259769:ios:283c58962720a296dc44a8',
    messagingSenderId: '792815259769',
    projectId: 'fyp-management-4dad2',
    storageBucket: 'fyp-management-4dad2.firebasestorage.app',
    iosBundleId: 'com.example.fypManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4nSKtGCTkJ61pbXdh0BdPYz4huS5_b2k',
    appId: '1:792815259769:ios:283c58962720a296dc44a8',
    messagingSenderId: '792815259769',
    projectId: 'fyp-management-4dad2',
    storageBucket: 'fyp-management-4dad2.firebasestorage.app',
    iosBundleId: 'com.example.fypManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFUEvMswmYSQE9iwfC8s39tvD7NvzFWnc',
    appId: '1:792815259769:web:e9e40117df0c0f9bdc44a8',
    messagingSenderId: '792815259769',
    projectId: 'fyp-management-4dad2',
    authDomain: 'fyp-management-4dad2.firebaseapp.com',
    storageBucket: 'fyp-management-4dad2.firebasestorage.app',
    measurementId: 'G-BJ8N7VC55R',
  );
}
